release: python manage.py migrate auth --fake-initial && python manage.py migrate --noinput && python manage.py init_db
web: gunicorn ddoswatchglobal.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
